# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta keywords'),
        ),
    ]
