# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_add_meta_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='intro',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Özet'),
        ),
    ]
